# Generated by Django 3.2.12 on 2022-07-17 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imsApp', '0009_product_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ids',
        ),
    ]
