# Generated by Django 3.2.12 on 2022-07-17 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imsApp', '0010_remove_product_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img',
        ),
    ]
