# Generated by Django 3.2.12 on 2022-07-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imsApp', '0011_remove_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default/default-avater.png', upload_to='uploads'),
        ),
    ]
