# Generated by Django 3.2.12 on 2022-07-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imsApp', '0012_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_item',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='invoice_item',
            name='tax',
            field=models.FloatField(default=0),
        ),
    ]
