# Generated by Django 3.2.12 on 2022-07-17 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imsApp', '0013_auto_20220717_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice_item',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='invoice_item',
            name='tax',
        ),
    ]
