# Generated by Django 3.2.12 on 2022-07-17 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imsApp', '0014_auto_20220717_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='media/default/default-avater.png', upload_to='uploads'),
        ),
    ]
